[package]
name = "led"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.17.0", features = ["v4", "serde"] }
anyhow = "1.0.98" # For generating unique identifiers
serde = { version = "1.0.219", features = ["derive"] }
